import re, json

FULL    = "/sessions/sharp-bold-pascal/mnt/mentat/knowledge/projects/enterprise-ai-concepts/enterprise-ai-concepts-full-138.md"
CURATED = "/sessions/sharp-bold-pascal/mnt/mentat/knowledge/projects/enterprise-ai-concepts/enterprise-ai-concepts-curated.md"
PUB     = "/sessions/sharp-bold-pascal/mnt/mentat/artefacts/published/"

# 12 source categories -> 5 display buckets (balanced grouping)
BUCKET = {
    "Foundations":"Foundations & Models",
    "Models & GenAI":"Foundations & Models",
    "Alignment":"Governance, Risk & Strategy",
    "Prompting & Context":"Data & Knowledge",
    "Data & Knowledge":"Data & Knowledge",
    "Agents":"Agents",
    "Architecture":"Platform & Operations",
    "Operations":"Platform & Operations",
    "Governance & Trust":"Governance, Risk & Strategy",
    "Security & Safety":"Governance, Risk & Strategy",
    "Transformation & Value":"Governance, Risk & Strategy",
    "Standards & Regulation":"Governance, Risk & Strategy",
}
# Muted editorial palette: {light-ground hex, dark-ground hex}
PALETTE = {
    "Foundations & Models":        {"l":"#2C6E7E","d":"#77BECC"},
    "Data & Knowledge":            {"l":"#4E7A3E","d":"#9CC98A"},
    "Agents":                      {"l":"#B0563F","d":"#E6A088"},
    "Platform & Operations":       {"l":"#9A7A2C","d":"#DEC074"},
    "Governance, Risk & Strategy": {"l":"#7A4468","d":"#C795B8"},
}
CATS = list(PALETTE.keys())

import base64 as _b64
_LOGODIR = "/sessions/sharp-bold-pascal/mnt/mentat/brand/assets/logo/"
LOGO_LIGHT = _b64.b64encode(open(_LOGODIR+"MENTAT-long-light.png","rb").read()).decode()
LOGO_DARK  = _b64.b64encode(open(_LOGODIR+"MENTAT-long-dark.png","rb").read()).decode()

def parse(path):
    rows=[]
    for line in open(path, encoding="utf-8"):
        if not line.startswith("| "): continue
        c=[x.strip() for x in line.strip().strip("|").split("|")]
        if len(c)!=7 or not c[0].isdigit(): continue
        rows.append({"id":int(c[0]),"category":BUCKET.get(c[1],c[1]),"concept":c[2],
            "definition":c[3],"importance":int(c[4]),
            "related":[r.strip() for r in c[5].split(",") if r.strip()],
            "sources":[s.strip() for s in c[6].split(",") if s.strip()]})
    rows.sort(key=lambda r:r["id"])
    return rows

TEMPLATE = r"""<!doctype html>
<!-- Generated artefact. Source: knowledge/projects/enterprise-ai-concepts.
     Design source: brand/03-Design-System.md (Marginalia). Regenerate via knowledge/projects/enterprise-ai-concepts/build_wordcloud.py. Do not edit this file as the source of truth. -->
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="color-scheme" content="light dark">
<title>__TITLE__ &middot; Mentat</title>
<meta name="description" content="__DESC__">
<link rel="icon" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32'%3E%3Crect width='32' height='32' fill='%23E6E8E6'/%3E%3Crect x='8' y='15' width='16' height='2' fill='%2326418F'/%3E%3C/svg%3E">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Archivo:wght@200;300;400;500;600&family=JetBrains+Mono:wght@400&display=swap" rel="stylesheet">
<style>
  :root{
    color-scheme:light;
    --stone:#E6E8E6; --stone-raised:#EFF0EE; --ink:#1F2124; --ink-70:#3E4145;
    --ink-55:#55585C; --ink-40:#6C6F73; --ink-20:#B7B9B7;
    --rule:rgba(31,33,36,0.16); --rule-faint:rgba(31,33,36,0.08);
    --pen:#26418F; --pen-hover:#1B3070;
    --font-sans:Archivo,"Helvetica Neue",Inter,system-ui,sans-serif;
    --font-mono:"Commit Mono",ui-monospace,"JetBrains Mono",monospace;
    --s-3:12px; --s-4:16px; --s-5:24px; --s-6:38px; --s-7:64px; --s-8:96px;
    --rail:150px; --gutter:38px; --content:720px; --page-max:1180px; --page-pad:52px;
    --ease:cubic-bezier(0.22,0.61,0.36,1);
  }
  :root[data-theme="dark"]{
    color-scheme:dark;
    --stone:#1C1E1C; --stone-raised:#252725; --ink:#E6E8E6; --ink-70:#C2C5C3;
    --ink-55:#9DA0A2; --ink-40:#7E8183; --rule:rgba(230,232,230,0.16);
    --rule-faint:rgba(230,232,230,0.08); --pen:#7B9AE8; --pen-hover:#9DB4EE;
  }
  @media (prefers-color-scheme:dark){
    :root:not([data-theme="light"]):not([data-theme="dark"]){
      color-scheme:dark;
      --stone:#1C1E1C; --stone-raised:#252725; --ink:#E6E8E6; --ink-70:#C2C5C3;
      --ink-55:#9DA0A2; --ink-40:#7E8183; --rule:rgba(230,232,230,0.16);
      --rule-faint:rgba(230,232,230,0.08); --pen:#7B9AE8; --pen-hover:#9DB4EE;
    }
  }
  *{box-sizing:border-box}
  html{-webkit-text-size-adjust:100%}
  body{margin:0;background:var(--stone);color:var(--ink);font-family:var(--font-sans);
    font-size:15px;line-height:1.7;font-weight:300;-webkit-font-smoothing:antialiased}
  .page{max-width:var(--page-max);margin-inline:auto;padding-inline:var(--page-pad)}
  @media (max-width:640px){.page{padding-inline:24px}}
  .header{display:flex;justify-content:space-between;align-items:center;
    padding-top:22px;padding-bottom:var(--s-7);gap:var(--s-4);flex-wrap:wrap}
  .wordmark{font-weight:600;font-size:14px;text-transform:uppercase;letter-spacing:.02em;color:var(--ink);
    text-decoration:none;border:0;display:inline-flex;align-items:center}
  .wordmark .logo{height:20px;width:auto;display:block}
  .wordmark .logo-dark{display:none}
  :root[data-theme="dark"] .wordmark .logo-light{display:none}
  :root[data-theme="dark"] .wordmark .logo-dark{display:block}
  @media (prefers-color-scheme:dark){
    :root:not([data-theme="light"]):not([data-theme="dark"]) .wordmark .logo-light{display:none}
    :root:not([data-theme="light"]):not([data-theme="dark"]) .wordmark .logo-dark{display:block}
  }
  .header-right{display:inline-flex;align-items:center;gap:var(--s-5)}
  .nav-link{color:var(--ink-55);font-size:13px;font-weight:400;text-decoration:none;border:0}
  .nav-link:hover{color:var(--ink)}
  .theme{display:inline-flex;border:1px solid var(--rule)}
  .theme-opt{font:inherit;font-size:12px;letter-spacing:.02em;line-height:1;padding:6px 12px;
    background:none;border:0;color:var(--ink-55);cursor:pointer}
  .theme-opt+.theme-opt{border-left:1px solid var(--rule)}
  .theme-opt:hover{color:var(--ink)}
  .theme-opt[aria-pressed="true"]{color:var(--ink);font-weight:500;background:var(--stone-raised)}
  .layout{display:grid;grid-template-columns:var(--rail) 1fr}
  .rail{padding-right:var(--s-5);border-right:1px solid var(--rule);max-width:22ch}
  .tick{display:block;width:16px;height:2px;background:var(--pen);margin-bottom:var(--s-3)}
  .caption{font-size:11px;line-height:1.7;font-weight:500;letter-spacing:.04em;
    text-transform:uppercase;color:var(--ink-55);margin:0}
  .rail-meta{font-size:13px;line-height:1.6;color:var(--ink-55);margin:var(--s-5) 0 0}
  .rail-meta b{color:var(--ink-70);font-weight:500}
  .content{padding-left:var(--gutter);max-width:none;min-width:0}
  @media (max-width:640px){
    .layout{grid-template-columns:1fr}
    .rail{border-right:0;border-bottom:1px solid var(--rule);padding-bottom:var(--s-4);
      margin-bottom:var(--s-5);max-width:none}
    .content{padding-left:0}
  }
  .opener{padding-top:8px;padding-bottom:var(--s-6)}
  .display-m{font-size:40px;line-height:1.08;font-weight:200;letter-spacing:-.030em;color:var(--ink);
    margin:0;animation:fade .24s var(--ease)}
  .display-m strong{font-weight:500}
  .standfirst{font-size:17px;line-height:1.7;font-weight:300;color:var(--ink-70);margin:32px 0 0;max-width:62ch}
  .lede{font-size:15px;line-height:1.7;font-weight:300;color:var(--ink-70);margin:22px 0 0;max-width:62ch}
  @media (max-width:640px){.display-m{font-size:32px}}
  a{color:var(--pen);text-decoration:none;border-bottom:1px solid var(--pen);padding-bottom:2px;
    transition:color .16s var(--ease),border-bottom-width .16s var(--ease)}
  a:hover{color:var(--pen-hover);border-bottom-width:2px}
  :focus-visible{outline:2px solid var(--pen);outline-offset:3px}
  .legend{display:flex;flex-wrap:wrap;gap:12px 22px;margin:var(--s-6) 0 0;
    padding-top:var(--s-5);border-top:1px solid var(--rule)}
  .legend-item{background:none;border:0;padding:0;cursor:pointer;font-family:inherit;font-size:12px;
    font-weight:500;letter-spacing:.02em;line-height:1.4;color:var(--catcol);opacity:1;
    display:inline-flex;align-items:baseline;gap:7px}
  .legend-item .n{font-family:var(--font-mono);font-size:11px;color:var(--ink-40);font-weight:400}
  .legend-item.off{color:var(--ink-20);opacity:.6}
  .legend-item:hover{text-decoration:underline;text-underline-offset:3px}
  .cloud-wrap{margin:var(--s-6) 0 0;border-top:1px solid var(--rule);padding-top:var(--s-6)}
  .cloud{text-align:center;line-height:2.05}
  .word{display:inline-block;margin:2px 10px;vertical-align:middle;white-space:nowrap;cursor:pointer;
    background:none;border:0;padding:0 1px;font-family:inherit;line-height:1;color:var(--wc);
    border-bottom:2px solid transparent;transition:opacity .16s var(--ease)}
  .word:hover{border-bottom-color:currentColor}
  .word.dim{opacity:.1}
  .word.sel{border-bottom-color:currentColor}
  .cloud-hint{font-size:13px;color:var(--ink-55);margin:var(--s-5) 0 0;text-align:left}
  .modal{position:fixed;inset:0;z-index:50;display:flex;align-items:flex-start;justify-content:center;
    padding:8vh 24px;overflow-y:auto}
  .modal[hidden]{display:none}
  .scrim{position:fixed;inset:0;background:rgba(31,33,36,.44)}
  :root[data-theme="dark"] .scrim{background:rgba(0,0,0,.60)}
  @media (prefers-color-scheme:dark){:root:not([data-theme="light"]) .scrim{background:rgba(0,0,0,.60)}}
  .panel{position:relative;background:var(--stone);border:1px solid var(--rule);max-width:560px;width:100%;
    padding:var(--s-6);animation:fade .18s var(--ease)}
  .m-close{position:absolute;top:12px;right:12px;background:none;border:0;font:inherit;font-size:12px;
    letter-spacing:.02em;color:var(--ink-55);cursor:pointer;padding:6px}
  .m-close:hover{color:var(--ink)}
  .m-eyebrow{font-size:11px;font-weight:500;letter-spacing:.04em;text-transform:uppercase;
    color:var(--catcol,var(--ink-55));margin:0 0 8px;padding-right:56px}
  .panel h2{font-size:24px;line-height:1.25;font-weight:400;letter-spacing:-.02em;color:var(--ink);
    margin:0;padding-right:56px}
  .m-imp{font-family:var(--font-mono);font-size:13px;color:var(--ink-55);margin:10px 0 0}
  .m-def{font-size:15px;line-height:1.7;font-weight:300;color:var(--ink-70);margin:18px 0 0}
  .m-rowlab{font-size:11px;font-weight:500;letter-spacing:.04em;text-transform:uppercase;
    color:var(--ink-55);margin:20px 0 6px}
  .m-links{display:flex;flex-wrap:wrap;gap:6px 16px}
  .m-links .rel{background:none;border:0;padding:0;cursor:pointer;font-family:inherit;font-size:14px;
    color:var(--pen);border-bottom:1px solid var(--pen);line-height:1.4}
  .m-links .rel:hover{color:var(--pen-hover);border-bottom-width:2px}
  .m-links .src{font-family:var(--font-mono);font-size:13px;color:var(--ink-55)}
  footer{margin-top:var(--s-8);padding:var(--s-5) 0 var(--s-7);border-top:1px solid var(--rule);
    display:flex;justify-content:space-between;flex-wrap:wrap;gap:var(--s-3);font-size:13px;color:var(--ink-55)}
  footer code{font-family:var(--font-mono);background:var(--stone-raised);padding:1px 5px}
  @keyframes fade{from{opacity:0}to{opacity:1}}
  @media (prefers-reduced-motion:reduce){*{animation:none!important;transition:none!important}}
</style>
</head>
<body>
<div class="page">
  <header class="header">
    <a class="wordmark" href="index.html" aria-label="Mentat"><img class="logo logo-light" src="data:image/png;base64,__LOGO_LIGHT__" alt="Mentat" height="20"><img class="logo logo-dark" src="data:image/png;base64,__LOGO_DARK__" alt="" aria-hidden="true" height="20"></a>
    <nav class="header-right">
      <a class="nav-link" href="index.html">Home</a>__NAVEXTRA__
      <div class="theme" role="group" aria-label="Colour theme">
        <button class="theme-opt" type="button" data-set="light">Light</button>
        <button class="theme-opt" type="button" data-set="dark">Dark</button>
      </div>
    </nav>
  </header>
  <div class="layout">
    <aside class="rail">
      <span class="tick" aria-hidden="true"></span>
      <p class="caption">__CAPTION__</p>
      <p class="rail-meta"><b>Size</b> is importance. <b>Colour</b> is category.</p>
      <p class="rail-meta">Select a word to read its definition. Select a category to isolate it.</p>
      <p class="rail-meta">One Markdown source. <span id="count"></span> concepts.__RAILEXTRA__</p>
    </aside>
    <main class="content">
      <section class="opener">
        <h1 class="display-m">__HEADING__</h1>
        <p class="standfirst">__STANDFIRST__</p>
        __EXPLAINER__
      </section>
      <div class="legend" id="legend"></div>
      <div class="cloud-wrap">
        <div class="cloud" id="cloud"></div>
        <p class="cloud-hint" id="hint"></p>
      </div>
      <footer>
        <span>Mentat, a knowledge operating system.</span>
      </footer>
    </main>
  </div>
</div>
<div class="modal" id="modal" hidden>
  <div class="scrim" data-close></div>
  <div class="panel" role="dialog" aria-modal="true" aria-labelledby="m-title">
    <button class="m-close" type="button" data-close aria-label="Close definition">Close &times;</button>
    <p class="m-eyebrow" id="m-eyebrow"></p>
    <h2 id="m-title"></h2>
    <p class="m-imp" id="m-imp"></p>
    <p class="m-def" id="m-def"></p>
    <p class="m-rowlab" id="m-rel-lab">Related concepts</p>
    <div class="m-links" id="m-rel"></div>
    <p class="m-rowlab">Educational sources</p>
    <div class="m-links" id="m-src"></div>
  </div>
</div>
<script>
  var DATA = __DATA__;
  var PALETTE = __PALETTE__;
  var CATS = __CATS__;
  (function(){
    var root=document.documentElement, opts=[].slice.call(document.querySelectorAll('.theme-opt'));
    var mq=window.matchMedia('(prefers-color-scheme: dark)');
    try{var s=localStorage.getItem('mentat-theme'); if(s) root.setAttribute('data-theme',s);}catch(e){}
    function eff(){var t=root.getAttribute('data-theme'); if(t==='dark'||t==='light')return t; return mq.matches?'dark':'light';}
    function sync(){var e=eff(); opts.forEach(function(o){o.setAttribute('aria-pressed',String(o.dataset.set===e));}); recolour();}
    opts.forEach(function(o){o.addEventListener('click',function(){root.setAttribute('data-theme',o.dataset.set);
      try{localStorage.setItem('mentat-theme',o.dataset.set);}catch(e){} sync();});});
    mq.addEventListener('change',sync);
    window.__effTheme=eff; window.__initTheme=function(){opts.forEach(function(o){o.setAttribute('aria-pressed',String(o.dataset.set===eff()));});};
  })();
  function catColor(cat){
    var dark = (window.__effTheme && window.__effTheme()==='dark');
    var p = PALETTE[cat]; if(!p) return 'var(--ink-55)';
    return dark ? p.d : p.l;
  }
  document.getElementById('count').textContent = DATA.length;
  var active={}; CATS.forEach(function(c){active[c]=true;});
  var selectedId=null, SPANS=[];
  var legendEl=document.getElementById('legend');
  CATS.forEach(function(cat){
    var n=DATA.filter(function(d){return d.category===cat;}).length;
    if(!n) return;
    var b=document.createElement('button');
    b.className='legend-item'; b.type='button'; b.dataset.cat=cat;
    b.style.setProperty('--catcol', catColor(cat));
    b.innerHTML=cat+' <span class="n">'+n+'</span>';
    b.addEventListener('click', function(){
      var allOn=CATS.every(function(c){return !hasCat(c)||active[c];});
      if(allOn){ CATS.forEach(function(c){active[c]=(c===cat);}); }
      else if(active[cat] && activeShownCats()===1){ CATS.forEach(function(c){active[c]=true;}); }
      else { active[cat]=!active[cat]; }
      syncLegend(); applyFilter();
    });
    legendEl.appendChild(b);
  });
  function hasCat(c){ return DATA.some(function(d){return d.category===c;}); }
  function activeShownCats(){ return CATS.filter(function(c){return hasCat(c)&&active[c];}).length; }
  function syncLegend(){ [].forEach.call(legendEl.children,function(b){ b.classList.toggle('off', !active[b.dataset.cat]); }); }
  var cloud=document.getElementById('cloud');
  function sizeFor(imp){ var v=imp*imp; return Math.round(12 + (v-16)/(100-16)*(54-12)); }
  function weightFor(imp){ return imp>=8?300 : imp>=6?400 : 500; }
  function buildCloud(){
    cloud.innerHTML=''; SPANS=[];
    var byImp=DATA.slice().sort(function(a,b){ return b.importance-a.importance || a.concept.toLowerCase().localeCompare(b.concept.toLowerCase()); });
    var items=[];
    byImp.forEach(function(d,i){ if(i%2===0) items.push(d); else items.unshift(d); });
    items.forEach(function(d){
      var el=document.createElement('button');
      el.type='button'; el.className='word'; el.textContent=d.concept;
      el.dataset.id=d.id; el.dataset.cat=d.category;
      el.style.fontSize=sizeFor(d.importance)+'px'; el.style.fontWeight=weightFor(d.importance);
      el.style.setProperty('--wc', catColor(d.category));
      el.title=d.concept+'  ·  importance '+d.importance+'/10  ·  '+d.category;
      el.addEventListener('click', function(){ select(d.id, el); });
      cloud.appendChild(el);
      SPANS.push({el:el, id:d.id, cat:d.category});
    });
    applyFilter();
  }
  function applyFilter(){
    var anyFilter=CATS.some(function(c){return hasCat(c)&&!active[c];});
    SPANS.forEach(function(s){ s.el.classList.toggle('dim', anyFilter && !active[s.cat]); });
    var shown=SPANS.filter(function(s){return active[s.cat];}).length;
    document.getElementById('hint').textContent =
      anyFilter ? (shown+' of '+DATA.length+' concepts shown. Select a highlighted category again to reset.')
                : (DATA.length+' concepts. The most important sit in the middle and grow outward.');
  }
  function markSelected(){ SPANS.forEach(function(s){ s.el.classList.toggle('sel', s.id===selectedId); }); }
  function recolour(){
    SPANS.forEach(function(s){ s.el.style.setProperty('--wc', catColor(s.cat)); });
    [].forEach.call(legendEl.children,function(b){ b.style.setProperty('--catcol', catColor(b.dataset.cat)); });
    var d=DATA.find(function(x){return x.id===selectedId;});
    if(d && modal){ modal.style.setProperty('--catcol', catColor(d.category)); }
  }
  var modal=document.getElementById('modal'), lastFocus=null;
  function onKey(e){ if(e.key==='Escape') closeModal(); }
  function openModal(){ modal.hidden=false; document.addEventListener('keydown',onKey); }
  function closeModal(){ modal.hidden=true; document.removeEventListener('keydown',onKey);
    SPANS.forEach(function(s){ s.el.classList.remove('sel'); }); selectedId=null;
    if(lastFocus && lastFocus.focus) lastFocus.focus(); }
  [].forEach.call(modal.querySelectorAll('[data-close]'),function(b){ b.addEventListener('click',closeModal); });
  function esc(s){return String(s).replace(/[&<>"]/g,function(m){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m];});}
  function select(id, fromEl){
    var d=DATA.find(function(x){return x.id===id;});
    if(!d) return;
    if(fromEl) lastFocus=fromEl;
    selectedId=id; markSelected();
    modal.style.setProperty('--catcol', catColor(d.category));
    document.getElementById('m-eyebrow').textContent=d.category+'  ·  #'+d.id;
    document.getElementById('m-title').textContent=d.concept;
    document.getElementById('m-imp').textContent='Importance '+d.importance+' / 10';
    document.getElementById('m-def').textContent=d.definition;
    var relEl=document.getElementById('m-rel');
    relEl.innerHTML=d.related.map(function(r){
      var t=DATA.find(function(x){return x.concept.toLowerCase()===r.toLowerCase();});
      return t ? '<button class="rel" type="button" data-id="'+t.id+'">'+esc(r)+'</button>'
               : '<span class="src">'+esc(r)+'</span>';
    }).join('');
    document.getElementById('m-rel-lab').style.display = relEl.children.length ? '' : 'none';
    document.getElementById('m-src').innerHTML=d.sources.map(function(s){return '<span class="src">'+esc(s)+'</span>';}).join('');
    [].forEach.call(relEl.querySelectorAll('.rel'),function(b){ b.addEventListener('click',function(){ select(+b.dataset.id); }); });
    openModal();
    var cl=modal.querySelector('.m-close'); if(cl) cl.focus();
  }
  buildCloud(); syncLegend(); if(window.__initTheme) window.__initTheme();
</script>
</body>
</html>
"""

def build(rows, out, srcfile, title, desc, caption, heading, standfirst, explainer, navextra, railextra):
    html = TEMPLATE
    repl = {
        "__DATA__": json.dumps(rows, ensure_ascii=False),
        "__PALETTE__": json.dumps(PALETTE, ensure_ascii=False),
        "__CATS__": json.dumps(CATS, ensure_ascii=False),
        "__SRCFILE__": srcfile, "__TITLE__": title, "__DESC__": desc,
        "__CAPTION__": caption, "__HEADING__": heading, "__STANDFIRST__": standfirst,
        "__EXPLAINER__": explainer, "__NAVEXTRA__": navextra, "__RAILEXTRA__": railextra,
        "__LOGO_LIGHT__": LOGO_LIGHT, "__LOGO_DARK__": LOGO_DARK,
    }
    for k,v in repl.items(): html = html.replace(k, v)
    open(PUB+out, "w", encoding="utf-8").write(html)
    from collections import Counter
    print("Wrote", out, len(rows), "concepts,", dict(Counter(r["category"] for r in rows)))

curated = parse(CURATED)

build(curated, "ai-concepts-wordcloud.html",
      "knowledge/projects/enterprise-ai-concepts/enterprise-ai-concepts-curated.md",
      "Enterprise AI vocabulary for the C-suite",
      "A curated, living map of the enterprise AI concepts leaders need in 2026. Sized by importance, grouped into five families. Keeping the vocabulary current is how executives keep authority over AI decisions.",
      "Enterprise AI vocabulary",
      "A working vocabulary for <strong>enterprise AI.</strong>",
      "The concepts that most shape strategy, value, governance and risk, curated for the C-suite. Sized by importance, grouped into five families, and generated from one source so it stays current.",
      '<p class="lede">The language of AI changes quickly. Terms that were unfamiliar a year ago now sit in budgets, board papers, and regulation. When the vocabulary drifts, so does the ability to ask a precise question, test a vendor&rsquo;s claim, or tell a real capability from a relabelled one. Keeping the words current is how leaders hold authority over decisions increasingly framed in them. The most important terms sit in the middle; read outward.</p>',
      "",
      "")
